version: '2'

services:
  spring-boot-service:
    build: ./boot
    ports:
      - 8081:8081

  ui:
    build: ./ui
    volumes:
      - ./ui:/usr/src/app
    ports:
      - 3000:3000
    depends_on:
      - spring-boot-service
